<section class="content-header">
          <h1>
            Editar Vocabulario
            <small>Taxonomias</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="taxonomia">taxonomias</a></li>
            <li class="active">Editar vocabulario</li>
          </ol>
</section>
        
<section class="content"> 

<div class="box">
<div class="box-body">

<?php if($this->_post()) print $this->message->getMsg(); ?>



<form id="form1" name="form1" method="post" action="" action-type="edit">

<table width="1016" border="0" cellpadding="5" cellspacing="0" class="table table-striped">
  <tr>
    <td width="130" align="right">Vocabulario</td>
    <td width="866"><input name="nome" type="text" id="nome" size="50" value="<?php print $view_vocabulario[0]['taxonomy'];  ?>" /></td>
    </tr>
  
  <tr>
    <td align="right">&nbsp;</td>
    <td><input type="submit" name="button" id="button" value="Salvar" class="save btn btn-default"/></td>
  </tr>
  </table>

</form>
