<section class="content-header">
          <h1>
            Lista de Vocabularios
            <small>Taxonomias</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">taxonomias</a></li>
            <li class="active">Listagem de Vocabularios</li>
          </ol>
</section>
        
<section class="content"> 

<div class="box">
<div class="box-body">

<table width="100%" border="0" cellpadding="5" cellspacing="1" style="font-size:12px;" class="table table-striped">
    <thead>
  <tr style="font-weight:bold">
    <td width="102" align="right">ID</td>
    <td width="422">Vocabulario</td>
    <td width="1342">Ações</td>
  </tr>
  </thead>
 <tbody class="table_content">
<?php  foreach($view_data as $dados ) { ?>
	
   <tr class="line">
    <td align="right"><?php print $dados['id_taxonomy']; ?></td>
    <td><a href="admin/taxonomia/termos/vocabulario/<?php print $dados['id_taxonomy']; ?>" title="listar termos"><?php print $dados['taxonomy']; ?></a></td>
    <td class="actions">
    	<a href="<?php print ih_current_path; ?>/termos/vocabulario/<?php print $dados['id_taxonomy']; ?>" title="listar termos">
        	<i class="fa fa-folder" style="font-size:18px;"></i>
        </a>  
    	<a href="<?php print ih_current_path; ?>/edit/id/<?php print $dados['id_taxonomy'] ?>" title="Editar taxonomia" class="edit lightbox_trigger">
        	<i class="fa fa-fw fa-edit" style="font-size:18px;"></i>
        </a>  
        <a href="javascript:void(0)"  class="del" data-controller="<?php print ih_current_path; ?>/del" title="Apagar Vocabulario" data-id="<?php print $dados['id_taxonomy']; ?>">
        	<i class="fa fa-trash-o" style="font-size:18px;"></i>
        </a>
    </td>

  </tr>
	
<?php  }  ?>
</tbody>
</table>

</div>
</div>
</section>
