<section class="content-header">
          <h1>
            Editar Modulo
            <small>Regerar estrutura</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">xcode</a></li>
            <li class="active">Edit module</li>
          </ol>
</section>
        
<section class="content"> 

<div class="box">
<div class="box-body">
      
	  
<?php if($this->_post()) $this->message->getMsg(); ?>
	  
<form action="" class="form-group" method="post" enctype="multipart/form-data" name="form">
  
  	<input type="hidden" name="id_controller" value="<?php print $this->_get('id'); ?>"  />
    <div class="row">
        <div class="col-md-10">
          <fieldset> 
          	<legend> Nome do modulo </legend>
            <input name="controller" type="text" placeholder="field name" class="form-control" required="required" value="<?php print $view_data_fields['controller']; ?>" />
          </fieldset>
        </div>
    </div>
	
    <div class="row">
        
        <div class="col-md-10">
        <fieldset> 
          <legend> Adicionar campos </legend>
                    
            <table class="table table-bordered table-striped">
              <tr>
                <td>Nome do campo</td>
                <td>Tipo do campo</td>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td>
                  <input name="field_name" id="field_name" type="text" class="form-control" />
                </td>
                <td>
                  <select name="tipo" id="field_type" class="form-control" >
                    <option value="textfield">Text</option>
                    <option value="textarea">Textarea</option>
                    <option value="select">Select</option>
					<option value="image">Imagem</option>
					<option value="file">Arquivo</option>
					<option value="radio">Radio Button</option>
                    <option value="checkbox">Checkbox</option>
					<option value="taxonomy">Taxonomia</option>
					<option value="entity">Entidade</option>
                  </select>
                </td>
                <td>
                  <input name="input" type="button" class="btn btn-default add_field" value="Add field" />
                </td>
              </tr>
			  <tr>
                <td><input name="field_machine_name" id="field_machine_name" type="text" class="form-control" /></td>
                <td></td>
                <td></td>
              </tr>
            </table>
            
            
            
        </fieldset>
		
    	</div>
                
    </div>
    
    <div class="row">
        
        <div class="col-md-10">
        <fieldset> 
          <legend> Lista de campos</legend>
                    
            <table class="table table-bordered table-striped draggable">
              <thead>
				<tr>
					<td width="32%">Nome do campo</td>
					<td width="32%">Tipo do campo</td>
					<td width="13%" style="text-align:center;">Grid Size</td>
					<td width="8%" style="text-align:center;">Coluna</td>
					<td width="15%" colspan="3" style="text-align:center;">Actions</td>
				</tr>
			  </thead>
			  <tbody class="table_content">
			  
			  <?php foreach($view_data_fields['field'] as $field) { ?>
				
                <?php if(!isset($field['deleted'])) { ?>
				
				<tr id="<?php print $field['field_machine_name'] ?>">

				<input type="hidden" class="<?php print $field['field_machine_name'] ?>_options" name="field[<?php print $field['field_machine_name'] ?>][options][<?php print $field['field_type'] ?>]" value="<?php print $field['options'][$field['field_type']] ?>" />
				<input type="hidden" class="input_field_name" name="field[<?php print $field['field_machine_name'] ?>][field_name]" value="<?php print $field['field_name'] ?>" />
				<input type="hidden" class="machine_name" name="field[<?php print $field['field_machine_name'] ?>][field_machine_name]" value="<?php print $field['field_machine_name'] ?>" />
				<input type="hidden" class="input_machine_name_old" name="field[<?php print $field['field_machine_name'] ?>][field_machine_name_old]" value="" />
				<input type="hidden" class="input_storage" name="field[<?php print $field['field_machine_name'] ?>][field_storage]" value="true" />
                <input type="hidden" class="field_multiple_values" name="field[<?php print $field['field_machine_name'] ?>][field_multiple_values]" value="<?php print $field['field_multiple_values'] ?>" />
				<input type="hidden" class="field_type" name="field[<?php print $field['field_machine_name'] ?>][field_type]" value="<?php print $field['field_type'] ?>" />
				<td class="field_name"><?php print $field['field_name'] ?></td>
				<td class="field_type"><?php print $field['field_type'] ?></td>
				<td width="10%" style="text-align:center;">
				  <select name="field[<?php print $field['field_machine_name'] ?>][grid]" id="grid_system" class="form-control">
				    <option value="1" <?php if($field['grid'] == 1) print 'selected'; ?> >1</option>
				    <option value="2" <?php if($field['grid'] == 2) print 'selected'; ?> >2</option>
				    <option value="3" <?php if($field['grid'] == 3) print 'selected'; ?> >3</option>
				    <option value="4" <?php if($field['grid'] == 4) print 'selected'; ?> >4</option>
				    <option value="5" <?php if($field['grid'] == 5) print 'selected'; ?> >5</option>
				    <option value="6" <?php if($field['grid'] == 6) print 'selected'; ?> >6</option>
				    <option value="7" <?php if($field['grid'] == 7) print 'selected'; ?> >7</option>
				    <option value="8" <?php if($field['grid'] == 8) print 'selected'; ?> >8</option>
				    <option value="9" <?php if($field['grid'] == 9) print 'selected'; ?> >9</option>
				    <option value="10" <?php if($field['grid'] == 10) print 'selected'; ?> >10</option>
				    <option value="11" <?php if($field['grid'] == 11) print 'selected'; ?> >11</option>
				    <option value="12" <?php if($field['grid'] == 12) print 'selected'; ?> >12</option>
				    </select></td>
				<td width="10%" style="text-align:center;">
					<input name="field[<?php print $field['field_machine_name'] ?>][colum_list]" type="checkbox" value="true" <?php if(isset($field['colum_list']) && $field['colum_list']) print 'checked' ?> />
				</td>
				<td style="text-align:center;">
					<a href="javascript:void(0)" class="del_row" data-storage='true'>
						<img src="templates/assets/images/icons/delete.png" width="16" />
					</a>
				</td>
				<td style="text-align:center;">
					<a href="javascript:void(0)" class="call_modal_field_options" data-machine-name="<?php print $field['field_machine_name'] ?>" data-name="<?php print $field['field_name'] ?>" title="Options">
						<img src="templates/assets/images/icons/edit.png" width="16" />
					</a>
				</td>
				<td style="text-align:center;">
					<a href="javascript:void(0)" class="drag-handle" title="Drag to re-order">
						<img src="templates/assets/images/icons/move.svg" width="16" />
					</a>
				</td>
				
				</tr>
                
			  <?php } ?>
			  <?php } ?>

			  </tbody>
            </table>
            
        </fieldset>
    	</div>
                
    </div>
    
    <div class="row">
        
        <div class="col-md-10">
        <fieldset> 
          <legend> Opções</legend>
                    
            <table width="261" class="table table-bordered table-striped draggable">
					
				<tr>
					<td width="35%">Usar Paginação</td>
					<td width="30%">
					  <input name="pagination" type="checkbox" id="pagination" value="true" checked="checked" />
					  <label for="pagination"></label>
					</td>
				</tr>
				

            </table>
            
        </fieldset>
    	</div>
                
    </div>
    
    
    
     

<input type="submit" class="btn btn-default" value="Gerar Estrutura" />

</form>

</div>
</div>
</section>
