<section class="content-header">
          <h1>
            <i class="fa fa-user"></i> Adicionar Pápel de usuário
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="users">users</a></li>
            <li class="active">Add new Role</li>
          </ol>
</section>
        
<section class="content"> 

<div class="box">
<div class="box-body">
      
	  
<?php if($this->_post()) $this->message->getMsg(); ?>


	  
<form action="" class="form-group" method="post" enctype="multipart/form-data" name="form">
  
  <fieldset> 
          <legend> Pápel de usuário </legend>
  	
    <div class="row">
        <div class="col-md-6">
          	<label> Pápel de usuário</label>
            <input name="name" type="text" placeholder="field name" class="form-control" required="required" id="name" />
        </div>
    </div>
    
    
    <fieldset> 
          <legend> Permissões </legend>
    
    <div class="row">
    	<div class="col-md-6"> 	
                    
            <table class="table table-bordered table-striped">
              <tr>
                <td><strong>Módulo</strong></td>
                <td align="center"><strong>Listar</strong></td>
                <td align="center"><strong>Adicionar</strong></td>
                <td align="center"><strong>Editar</strong></td>
                <td align="center"><strong>Excluir</strong></td>
              </tr>
              
              <tr>
                <td>Usuários</td>
                <td align="center"><input type="checkbox" value="true" name="permissao[users][index_action]" id="checkbox" /></td>
                <td align="center"><input type="checkbox" value="true" name="permissao[users][add]" id="checkbox2" /></td>
                <td align="center"><input type="checkbox" value="true" name="permissao[users][edit]" id="checkbox3" /></td>
                <td align="center"><input type="checkbox" value="true" name="permissao[users][del]" id="checkbox4" /></td>
              </tr>
              
              <tr>
                <td>Taxonomias</td>
                <td align="center"><input type="checkbox" value="true" name="permissao[taxonomia][index_action]" id="checkbox" /></td>
                <td align="center"><input type="checkbox" value="true" name="permissao[taxonomia][add]" id="checkbox2" /></td>
                <td align="center"><input type="checkbox" value="true" name="permissao[taxonomia][edit]" id="checkbox3" /></td>
                <td align="center"><input type="checkbox" value="true" name="permissao[taxonomia][del]" id="checkbox4" /></td>
              </tr>
			  
              
               <?php foreach( $this->init->xcodeModel->getAll() as $_menu ) { ?>
              
              <tr>
                <td><?php print $_menu['controller'] ?></td>
                <td align="center">
                	<input type="checkbox" value="true" name="permissao[<?php print strtolower(functions::removeSpecialChars($_menu['controller'])); ?>][index_action]" id="permissao_view" /></td>
                <td align="center">
                <input type="checkbox" value="true" name="permissao[<?php print strtolower(functions::removeSpecialChars($_menu['controller'])); ?>][add]" id="permissao_add" /></td>
                <td align="center">
                <input type="checkbox" value="true" name="permissao[<?php print strtolower(functions::removeSpecialChars($_menu['controller'])); ?>][edit]" id="permissao_edit" /></td>
                <td align="center">
                <input type="checkbox" value="true" name="permissao[<?php print strtolower(functions::removeSpecialChars($_menu['controller'])); ?>][del]" id="permissao_del" /></td>
              </tr>
              
              <?php } ?>
              
            </table>

     </div>
    </div>
 </fieldset>  
     

<input type="submit" class="btn btn-default" value="Adicionar Pápel" />

</form>

</div>
</div>
</section>
