<section class="content-header">
    <h1>
        <i class="fa fa-user"></i> Editar Usuário
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="users">users</a></li>
        <li class="active">Edit user</li>
    </ol>
</section>

<section class="content"> 

    <div class="box">
        <div class="box-body">
        
            <?php if($this->_post()) $this->message->getMsg(); ?>
        
            <form action="" class="form-group" method="post" enctype="multipart/form-data" name="form">
        
                <fieldset> 
                    <legend> Adicionar Pápel de Usuário </legend>
                
                    <div class="row">
                        <div class="col-md-6">
                            <label> Pápel de usuário</label>
                            <input name="name" type="text" placeholder="field name" value="<?php print $view_role['user_type'] ?>" class="form-control" required="required" id="name" />
                        </div>
                    </div>
                
                </fieldset>
                
                <fieldset> 
                    <legend> Permissões </legend>
                
                    <div class="row">
                        <div class="col-md-12"> 	
                            <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
                            <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

                            <?php foreach ($view_modulos as $modelo): ?>
                                <div style="margin: 20px 0;">
                                <label for="permissions"><?php echo strtoupper($modelo['modulo']); ?></label>
                                <?php
                                
                                    // echo "<pre>";
                                    // print_r($modelo['modulo']);
                                    // print_r($view_permission[$modelo['modulo']]);
                                    // echo "</pre>";
                                ?>
                                <select id="permissions" name="permissions[<?php echo $modelo['modulo']; ?>][]" class="" style="width: 100%;" multiple="multiple">
                                    <?php foreach ($modelo['funcoes'] as $funcao): ?>
                                        <option value="<?php echo $funcao; ?>" ><?php echo $funcao; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                                <?php endforeach; ?>

                            <script>
                                $(document).ready(function() {
                                    $('#permissions').select2();
                                });
                            </script>
                        </div>
                    </div>
                
                </fieldset>  
        
        <div class="row">
            <div class="col-md-6">
                <input type="submit" class="btn btn-primary" value="Criar Novo Papel" />
            </div>
            <div class="col-md-6 text-right">
                <a href="admin/users/roles" class="btn btn-info">Voltar</a>
            </div>
        </div>
        
            </form>
        
        </div>
    </div>
</section>
