<section class="content-header">
          <h1>
            Detalhes {controller} 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{controller}">{controller}</a></li>
            <li class="active">Detalhes de {controller}</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">

    
  		{fields_details}

      </div>
    </div>
</section>