<section class="content-header">
          <h1>
            Editar {controller} 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{controller}">{controller}</a></li>
            <li class="active">Lista de {controller}</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">
        

<div style="padding:10px;"> <?php if($_POST) { $this->message->getMsg(); } ?> </div>

<form id="form1" name="form1" method="post" enctype="multipart/form-data" action="">

    
  		{fields_edit}
  		<div class="col-xs-12">  
			<button type="submit" class="btn btn-default">Editar</button>
		</div>


</form>


        
        </div>
    </div>
</section>