<section class="content-header">
          <h1>
            Cadastrar {controller}
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">{controller}</a></li>
            <li class="active">Adicionar novo {controller}</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">
     
            
            <?php if($_POST) { ?><div style="padding:10px;"> <?php $this->message->getMsg(); ?> </div> <?php } ?> 
            
            <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1" >

                
                    {fields_add}
              		<div class="col-xs-12">  
						<button type="submit" class="btn btn-default">Cadastrar</button>
					</div>
            
            </form>

        
        </div>
    </div>
</section>