<section class="content-header">
          <h1>
            Lista de {controller} 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{controller}">{controller}</a></li>
            <li class="active">Lista de {controller}</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">
        

    <table width="100%" border="0" cellpadding="5" cellspacing="1" style="font-size:12px;" class="table table-striped">
      <tr style="font-weight:bold">
        <td width="49">ID</td>
        {labels_view}
        <td width="138">Ações</td>
      </tr>
    
    <?php  foreach($view_list as $dados ) { ?>
        
       <tr class="line">
        <td><?php print $dados['{id}']; ?></td>
        {fields_view}
        <td class="actions">
        	<a href="<?php print ih_current_path; ?>/details/id/<?php print $dados['{id}'] ?>">
				<i class="fa fa-files-o"></i>
			</a>  
            <a href="<?php print ih_current_path; ?>/edit/id/<?php print $dados['{id}'] ?>">
				<i class="fa fa-edit"></i>
			</a>   
            <a href="javascript:void(0)" class="del" data-controller="<?php print ih_current_path; ?>/del" title="Apagar registro" data-id="<?php print $dados['{id}']; ?>">
                <i class="fa fa-ban"></i>
            </a>
        </td>
    
      </tr>
        
    <?php  }  ?>
    
    </table>

        
        </div>
    </div>
    
    <?php $this->pagination->paginate()?>
    
</section>