<section class="content-header">

          <h1>

            Cadastrar Exames

            <small></small>

          </h1>

          <ol class="breadcrumb">

            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

            <li><a href="#">Exames</a></li>

            <li class="active">Adicionar novo Exames</li>

          </ol>

</section>

        

<section class="content"> 



    <div class="box">

        <div class="box-body">

     

            

            <?php if($_POST) { ?><div style="padding:10px;"> <?php $this->message->getMsg(); ?> </div> <?php } ?> 

            

            <form action="" method="post" enctype="multipart/form-data" name="exame_add" id="exame_add" >



                

                    <div class="col-xs-12 name-exame type-textfield">

								<div class="form-group fields">

									<label for="exame">Exame</label>

									<input name="exame" type="textfield" value="" class="form-control" id="exame">

								</div>

							</div>

<div class="col-xs-12 name-paciente type-textfield">

								<div class="form-group fields">

									<label for="paciente">Paciente</label>

									<input name="paciente" type="textfield" value="" class="form-control" id="paciente">

								</div>

							</div>

<div class="col-xs-6 name-codigo_paciente type-textfield">

								<div class="form-group fields">

									<label for="codigo_paciente">Código Paciente</label>

									<input name="codigo_paciente" type="textfield" value="" class="form-control" id="codigo_paciente">

								</div>

							</div>

<div class="col-xs-6 name-email type-textfield">

								<div class="form-group fields">

									<label for="email">Email</label>

									<input name="email" type="textfield" value="" class="form-control" id="email">

								</div>

							</div>

<div class="col-xs-4 name-data_nascimento type-textfield">

								<div class="form-group fields">

									<label for="data_nascimento">Data Nascimento</label>

									<input name="data_nascimento" type="textfield" value="" class="form-control" id="data_de_nascimento">

								</div>

							</div> 


<div class="col-xs-3 type-textfield"> 
	<div class="form-group fields" style="margin-top: 25px;">
		<input type="checkbox" name="assinatura" id="has_assign" value="1"> <label>Assinatura ? </label>
	</div>
</div>

<div class="col-xs-5 name-pdf type-textarea">

								<div class="form-group fields">

									<label for="dados">PDF</label>

									<input type="file" name="pdf" id="pdf" class="form-control" />

									<input name="pdf_hidden" class="pdf_hidden" type="hidden" value="" />

								</div>

							</div>                    

                    <div class="load" style="display:none;">

                    	<div class="spinner" style="float:left">

							<div class="bounce1"></div>

							<div class="bounce2"></div>

							<div class="bounce3"></div>

						</div>

                    	<div style="float:left;" class="msg-status"> Aguarde... </div>

                    </div>



              		<div class="col-xs-12">  

						<button type="submit" class="btn btn-default salvar-exame">Cadastrar</button>

					</div>

            

            </form>



        

        </div>

    </div>

</section>