<section class="content-header">

          <h1>

            Editar Exames 

            <small></small>

          </h1>

          <ol class="breadcrumb">

            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

            <li><a href="Exames">Exames</a></li>

            <li class="active">Lista de Exames</li>

          </ol>

</section>

        

<section class="content"> 



    <div class="box">

        <div class="box-body">

        



 <?php if($_POST) { ?><div style="padding:10px;"> <?php $this->message->getMsg(); ?> </div> <?php } ?> 



<form name="exame_add" id="exame_add" method="post" enctype="multipart/form-data" action="" >



    

  		<div class="col-xs-12 name-exame type-textfield">

								<div class="form-group fields">

									<label for="exame">Exame</label>

									<input name="exame" type="textfield" value="<?php print html_entity_decode($view_data[0]["exame"]);  ?>" class="form-control" id="exame">

								</div>

							</div>

<div class="col-xs-12 name-paciente type-textfield">

								<div class="form-group fields">

									<label for="paciente">Paciente</label>

									<input name="paciente" type="textfield" value="<?php print $view_data[0]["paciente"];  ?>" class="form-control" id="paciente">

								</div>

							</div>

<div class="col-xs-6 name-codigo_paciente type-textfield">

								<div class="form-group fields">

									<label for="codigo_paciente">Código Paciente</label>

									<input name="codigo_paciente" type="textfield" value="<?php print $view_data[0]["codigo_paciente"];  ?>" class="form-control" id="codigo_paciente">

								</div>

							</div>

<div class="col-xs-6 name-email type-textfield">

								<div class="form-group fields">

									<label for="email">Email</label>

									<input name="email" type="textfield" value="<?php print $view_data[0]["email"];  ?>" class="form-control" id="email">

								</div>

							</div>

<div class="col-xs-6 name-data_nascimento type-textfield">

								<div class="form-group fields">

									<label for="data_nascimento">Data Nascimento</label>

									<input name="data_nascimento" type="textfield" value="<?php print $view_data[0]["data_nascimento"];  ?>" class="form-control" id="data_de_nascimento">

								</div>

							</div>

							<div class="col-xs-2 type-textfield"> 
								<div class="form-group fields" style="margin-top: 25px;">
									<input type="checkbox"  name="assinatura" id="has_assign" <?php if($view_data[0]["assinatura"]) print 'checked'; ?> value="1"> <label>Assinatura ? </label>
								</div>
							</div>


							<div class="col-xs-4 name-pdf type-file">


									<label for="dados">PDF</label>

									<input type="file" name="pdf" id="pdf" class="form-control" />

									<input name="pdf_hidden" class="pdf_hidden" type="hidden" value="<?php print $view_data[0]["pdf"];  ?>" />

		                            <input name="pdf_old" class="" type="hidden" value="<?php print $view_data[0]["pdf"];  ?>" />

		                            <a href="themes/files/uploads/<?php print $view_data[0]["pdf"]; ?>">Link PDF</a>


							</div>



<div class="col-xs-6 name-login type-textfield">

								<div class="form-group fields">

									<label for="login">Login</label>

									<input name="login" type="textfield" value="<?php print $view_data[0]["login"];  ?>" class="form-control" id="login">

								</div>

							</div>

<div class="col-xs-6 name-senha type-textfield">

								<div class="form-group fields">

									<label for="senha">Senha</label>

									<input name="senha" type="textfield" value="<?php print $view_data[0]["senha"];  ?>" class="form-control" id="senha">

								</div>

							</div>

							 <div class="load" style="display:none;">

                    	<div class="spinner" style="float:left">

							<div class="bounce1"></div>

							<div class="bounce2"></div>

							<div class="bounce3"></div>

						</div>

                    	<div style="float:left;" class="msg-status"> Aguarde... </div>

                    </div>

  		<div class="col-xs-12">  

			<button type="submit" class="btn btn-default salvar-exame">Editar</button>

		</div>





</form>





        

        </div>

    </div>

</section>