<script> 

$(function(){

})

</script>

<style type="text/css">

  body {
    font-family: Helvetica;
    color: #333;
    margin: 0;
    padding: 0;
    top: 0;
    display: table;
    width: 100%;
  }

  .page {
    width:1240px; 
    height:1724px; 
    margin:0 auto;
    position:relative; 
    margin-top:50px;
  }

</style>



<section class="content-header">

  <h2 style="float: left;    margin-left: 40%;">

    Resultado de Exame Ceman

    <small></small>

  </h2>

  <a href="users/logout" style="float: right; padding: 20px;">Sair</a>

</section>

        

<section class="content">


    <div class="box">

        <div class="box-body">   




        <?php 


        if(is_array($view_files)) {
          foreach ($view_files as $file) { ?>       

          <div class="page" data-page="1" style="background:url(themes/files/resultados/<?php print $view_folder; ?>/<?php print $file; ?>) center top no-repeat; ">   

        </div>

        <?php } } else {

            if(!$this->init->user['assinatura']) {
              print '<a href="http://sistemautomato.com.br/ceman/themes/files/uploads/'.$this->init->user['pdf'].'" style="
    display: block;
    position: absolute;
    text-align: center;
    width: 100%;
    margin-top: 80px;
"> Visualizar exame</a>';
            }

          } ?>


      </div>

    </div>

</section>