<section class="content-header">
          <h1>
            Cadastrar Médicos
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Médicos</a></li>
            <li class="active">Adicionar novo Médicos</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">
     
            
            <?php if($_POST) { ?><div style="padding:10px;"> <?php $this->message->getMsg(); ?> </div> <?php } ?> 
            
            <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1" >

                
                    <div class="col-xs-12 name-nome type-textfield">
								<div class="form-group fields">
									<label for="nome">Médico</label>
									<input name="nome" type="textfield" value="" class="form-control" id="nome">
								</div>
							</div>
<div class="col-xs-6 name-crm type-textfield">
								<div class="form-group fields">
									<label for="crm">CRM</label>
									<input name="crm" type="textfield" value="" class="form-control" id="crm">
								</div>
							</div>
<div class="col-xs-6 name-especialidade type-textfield">
								<div class="form-group fields">
									<label for="especialidade">especialidade</label>
									<input name="especialidade" type="textfield" value="" class="form-control" id="especialidade">
								</div>
							</div>
<div class="col-xs-6 name-assinatura type-image">
								<div class="form-group fields">
									<label for="assinatura">assinatura</label>
									<input type="file" name="assinatura" id="assinatura" class="form-control" />
								</div>
							</div>

              		<div class="col-xs-12">  
						<button type="submit" class="btn btn-default">Cadastrar</button>
					</div>
            
            </form>

        
        </div>
    </div>
</section>