<section class="content-header">
          <h1>
            Detalhes Médicos 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="Médicos">Médicos</a></li>
            <li class="active">Detalhes de Médicos</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">

    
  		<div class="col-xs-12">
						<div class="form-group fields">
							<label for="nome">Médico</label>
							<?php print $view_data[0]["nome"];  ?>
						</div>
					 </div>
<div class="col-xs-6">
						<div class="form-group fields">
							<label for="crm">CRM</label>
							<?php print $view_data[0]["crm"];  ?>
						</div>
					 </div>
<div class="col-xs-6">
						<div class="form-group fields">
							<label for="especialidade">especialidade</label>
							<?php print $view_data[0]["especialidade"];  ?>
						</div>
					 </div>
<div class="col-xs-6">
						<div class="form-group fields">
							<label for="assinatura">assinatura</label>
							<?php print $view_data[0]["assinatura"];  ?>
						</div>
					 </div>


      </div>
    </div>
</section>