<section class="content-header">
          <h1>
            Lista de Médicos 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="Médicos">Médicos</a></li>
            <li class="active">Lista de Médicos</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">
        

    <table width="100%" border="0" cellpadding="5" cellspacing="1" style="font-size:12px;" class="table table-striped">
      <tr style="font-weight:bold">
        <td width="49">ID</td>
        <td>Médico</td>
<td>CRM</td>

        <td width="200">Ações</td>
      </tr>
    
    <?php  foreach($view_list as $dados ) { ?>
        
       <tr class="line">
        <td><?php print $dados['id_medicos']; ?></td>
        <td><?php print $dados["nome"]; ?></td>
<td><?php print $dados["crm"]; ?></td>

        <td class="actions text-right">
        	<a class="btn btn-success ml-1"href="<?php print ih_current_path; ?>/details/id/<?php print $dados['id_medicos'] ?>">
				<i class="fa fa-files-o"></i>
			</a>  
            <a class="btn btn-success ml-1"href="<?php print ih_current_path; ?>/edit/id/<?php print $dados['id_medicos'] ?>">
				<i class="fa fa-edit"></i>
			</a>   
            <a href="javascript:void(0)" class="del btn btn-success ml-1" data-controller="<?php print ih_current_path; ?>/del" title="Apagar registro" data-id="<?php print $dados['id_medicos']; ?>">
                <i class="fa fa-ban  "></i>
            </a>
        </td>
    
      </tr>
        
    <?php  }  ?>
    
    </table>

        
        </div>
    </div>
    
    <?php $this->pagination->paginate()?>
    
</section>