<?php  foreach($view_data as $dados ) { ?>
	
   <tr class="line">
    <td align="right"><?php print $dados['id_taxonomia']; ?></td>
    <td><a href="taxonomia/termos/vocabulario/<?php print $dados['id_taxonomia']; ?>" title="listar termos"><?php print $dados['value']; ?></a></td>
    <td class="actions">
    	<a href="taxonomia/termos/vocabulario/<?php print $dados['id_taxonomia']; ?>" title="listar termos"><img src="assets/icons/table.png" width="16" height="16" /></a>  
    	<a href="taxonomia/edit/id/<?php print $dados['id_taxonomia'] ?>" title="Editar taxonomia" class="edit lightbox_trigger"><img src="assets/imagens/icons/edit.png" width="16" height="16" /></a>  
        <a href="javascript:void(0)" class="del" data-controller="taxonomia/del" title="Apagar Vocabulario" data-id="<?php print $dados['id_taxonomia']; ?>">
        	<img src="assets/imagens/icons/delete.png" width="16" height="16" />
        </a>
    </td>

  </tr>
	
<?php  }  ?>