<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Login Administração</title>

<base href="<?php echo PATH; ?>"  />


<script src="assets/js/jquery-1.7.2.min.js"> </script>
<script src="assets/js/function.js"> </script>




<style type="text/css">

body{ background-color: #108d9d; font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#666}
.containner { margin:0 auto; width:600px}

.containner .login {height:290px; margin:auto; padding:20px 70px; margin-top:15%; }
.containner .login .toptxt {padding:20px 10px; text-align:center;}
.containner .login .form { }

/*.containner .login { width:400px; height:250px; margin:auto; padding:20px;  background:url(imagens/key.png) no-repeat; background-position:300px 160px; background-color:#fff; border:solid 1px #dfdfdf; margin-top:40%; }*/
.porwered { text-align:right; padding:5px; color:#666; width:460px; margin: -50px auto 0 auto;}

input { border-radius:10px; margin-bottom:5px; }
input[type=text] { padding:10px; font-size:12px; color:#333; width:100%; border:solid 1px #ccc} 
input[type=password]{ padding:10px; font-size:12px; color:#333; width:100%; border:solid 1px #ccc} 
input[type=button]{ background-color:#f6f6f6; padding:3px 10px; border:solid 1px #cdcdcd; }
input[type=button]:hover{background-color:#eeffdd; border:solid 1px #b0cf9c; color:#6b7e5f}
/*input { padding:5px;} */

#mensagem{ padding-top:10px; }

#loading{ padding:8px; background:#FFF; display:none; width:40px; border-radius:5px; opacity:0.7 }
</style>
</head>

<body>

<div class="containner">

<div class="login">
        
        <div class="toptxt"></div>
    <form id="form1" name="form1" method="post" action="">
                  
<div class="form"> 
             
              <table width="100%" border="0" cellpadding="1" cellspacing="1">
                <tr>
                  <td width="317"><input type="text" name="user" id="user" placeholder="Usuário"  /></td>
                </tr>
                <tr>
                  <td><input type="password" name="pass" id="pass" placeholder="Senha" /></td>
                </tr>
                <tr>
                  <td height="34" align="center"><a href="javascript:void(0)"  id="login">Login</a><div id="loading"> <img src="assets/imagens/ajax-loader.gif"  /></div></td>
                </tr>
            </table>
 </div>               
                
    </form>
   		   <div id="mensagem"></div> 
           
  </div>

        

</div>







</body>
</html>