<!DOCTYPE html>
<html>
<head>
	<title>Cartao de paciente</title>
	<meta charset="UTF-8">


<style type="text/css">

body {
    font-size: 13px;
    font-family: helvetica;
    line-height: 10px;
}

</style>

<script type="text/javascript">
	
</script>


</head>
<body>


<div> 

<h3><?php print $view_data[0]['nome']; ?></h3>
<?php if (empty($view_data[0]['cpf'])): ?>
    <p style=""><strong>Usuário: </strong><?php print $view_data[0]['codigo_paciente']; ?><strong> - Senha: </strong><?php print $view_data[0]['senha']; ?></p>
<?php else: ?>
    <p style=""><strong>Usuário: </strong><?php print $view_data[0]['cpf']; ?><strong> - Senha: </strong><?php print $this->formatDateTimeToBR($view_data[0]['data_nascimento']); ?></p>
<?php endif; ?>
<p style="font-size: 10px;">Acesse pela aba de exames, ou pelo endereço: 
<?php if ($view_data[0]['clinica'] == 'ceman'): ?>
https://exames.cemanmogi.com.br/
<?php elseif ($view_data[0]['clinica'] == 'imason'): ?>
https://exames.imason.com.br/
<?php endif; ?>
</p>
</div>


</body>
</html>