<!DOCTYPE html>
<html>
<head>
	<title>Cartao de paciente</title>
	<meta charset="UTF-8">


<style type="text/css">

body {
    font-size: 13px;
    font-family: helvetica;
    line-height: 10px;
}

</style>

<script type="text/javascript">
	
</script>


</head>
<body>


<div> 

<h3><?php print $view_data[0]['nome']; ?></h3>
<p style=""><strong>Usuário: </strong><?php print $view_data[0]['codigo_paciente']; ?><strong> - Senha: </strong><?php print $view_data[0]['senha']; ?></p>
<p style="font-size: 10px;">Acesse pela aba de exames,  ou pelo endereço: http://http://159.89.131.30/system</p>

</div>


</body>
</html>