<section class="content-header">
          <h1>
            Cadastrar <?php if($this->_get('paciente')) { print 'Dependente'; } else { print 'Pacientes'; } ?> 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Pacientes</a></li>
            <li class="active">Adicionar novo Pacientes</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">
     
            
            <?php if($_POST) { ?><div style="padding:10px;"> <?php $this->message->getMsg(); ?> </div> <?php } ?> 
            
            <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1" >

                	<?php if(isset($view_responsavel)) { ?>

                		
            		<div class="col-xs-12 name-nome type-textfield">
						<div class="form-group fields">
							<label for="responsavel">Responsável</label>
							<input name="responsavel" type="textfield" value="<?php print $view_responsavel[0]['nome'] ?>" class="form-control" id="responsavel" readonly="readonly">
						</div>
					</div>

					<?php } ?> 

                    <div class="col-xs-12 name-nome type-textfield">
								<div class="form-group fields">
									<label for="nome">Nome</label>
									<input name="nome" type="textfield" value="" class="form-control" id="nome">
								</div>
							</div>
<div class="col-xs-3 name-codigo_paciente type-textfield">
								<div class="form-group fields">
									<label for="codigo_paciente">Código Paciente</label>
									<input name="codigo_paciente" type="textfield" value="" class="form-control" id="codigo_paciente">
								</div>
							</div>
<div class="col-xs-3 name-data_nascimento type-textfield">
								<div class="form-group fields">
									<label for="data_nascimento">Data Nascimento</label>
									<input name="data_nascimento" type="textfield" value="" class="form-control" id="data_nascimento">
								</div>
							</div>
<div class="col-xs-6 name-email type-textfield">
								<div class="form-group fields">
									<label for="email">Email</label>
									<input name="email" type="textfield" value="" class="form-control" id="email">
								</div>
							</div>
<div class="col-xs-6 name-telefone type-textfield">
								<div class="form-group fields">
									<label for="telefone">Telefone</label>
									<input name="telefone" type="textfield" value="" class="form-control" id="telefone">
								</div>
							</div>
<div class="col-xs-6 name-celular type-textfield">
								<div class="form-group fields">
									<label for="celular">Celular</label>
									<input name="celular" type="textfield" value="" class="form-control" id="celular">
								</div>
							</div>

              		<div class="col-xs-12">  
						<button type="submit" class="btn btn-default">Cadastrar</button>
					</div>
            
            </form>

        
        </div>
    </div>
</section>

<div>
	
	<?php if(isset($view_responsavel)) { ?>

		<a href="admin/pacientes/index/paciente/<?php print $this->_get('paciente'); ?>" class="btn btn-primary" style="margin-top: 15px;" >voltar para lista de dependentes</a>

	<?php } ?> 	
</div>


<script type="text/javascript">
	$(function(){

			$('#data_nascimento').mask('99/99/9999');

	});
</script>