<section class="content-header">
          <h1>
            Detalhes Pacientes 
            <small></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="Pacientes">Pacientes</a></li>
            <li class="active">Detalhes de Pacientes</li>
          </ol>
</section>
        
<section class="content"> 

    <div class="box">
        <div class="box-body">

    
  		<div class="col-xs-12">
						<div class="form-group fields">
							<label for="nome">Nome</label>
							<?php print $view_data[0]["nome"];  ?>
						</div>
					 </div>
<div class="col-xs-3">
						<div class="form-group fields">
							<label for="codigo_paciente">Código Paciente</label>
							<?php print $view_data[0]["codigo_paciente"];  ?>
						</div>
					 </div>
<div class="col-xs-3">
						<div class="form-group fields">
							<label for="data_nascimento">Data Nascimento</label>
							<?php print $view_data[0]["data_nascimento"];  ?>
						</div>
					 </div>
<div class="col-xs-6">
						<div class="form-group fields">
							<label for="email">Email</label>
							<?php print $view_data[0]["email"];  ?>
						</div>
					 </div>
<div class="col-xs-6">
						<div class="form-group fields">
							<label for="telefone">Telefone</label>
							<?php print $view_data[0]["telefone"];  ?>
						</div>
					 </div>
<div class="col-xs-6">
						<div class="form-group fields">
							<label for="celular">Celular</label>
							<?php print $view_data[0]["celular"];  ?>
						</div>
					 </div>


      </div>
    </div>
</section>