<section class="content-header">
    <h1>
        Editar Pacientes
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="Pacientes">Pacientes</a></li>
        <li class="active">Editar Pacientes</li>
    </ol>
</section>

<section class="content"> 
    <div class="box">
        <div class="box-body">
            <?php if($_POST) { ?>
                <div class="alert alert-info" role="alert"> 
                    <?php $this->message->getMsg(); ?> 
                </div> 
            <?php } ?> 

            <form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input name="nome" type="text" value="<?php print $view_data[0]["nome"]; ?>" class="form-control" id="nome">
                    <input type="hidden" name="senha" value="<?php print $view_data[0]['senha']; ?>" id="senha">
                </div>
                
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="codigo_paciente">Código Paciente</label>
                        <input name="codigo_paciente" type="text" value="<?php print $view_data[0]["codigo_paciente"]; ?>" class="form-control" id="codigo_paciente">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="data_nascimento">Data Nascimento</label>
                        <input name="data_nascimento" type="text" value="<?php print date('d/m/Y', strtotime($view_data[0]["data_nascimento"])); ?>" class="form-control" id="data_nascimento">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="cpf">CPF</label>
                        <input name="cpf" type="text" value="<?php print $view_data[0]["cpf"]; ?>" class="form-control" id="cpf">
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="email">Email</label>
                        <input name="email" type="email" value="<?php print $view_data[0]["email"]; ?>" class="form-control" id="email">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="telefone">Telefone</label>
                        <input name="telefone" type="text" value="<?php print $view_data[0]["telefone"]; ?>" class="form-control" id="telefone">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="celular">Celular</label>
                        <input name="celular" type="text" value="<?php print $view_data[0]["celular"]; ?>" class="form-control" id="celular">
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-6 text-left">  
                        <button type="submit" id="salvar" class="btn btn-primary">Salvar</button>
                    </div>
                    <div class="col-xs-6 text-right">
                        <a href="/admin/pacientes" class="btn btn-secondary">Voltar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<script src="app/pacientes/assets/pacientes.js?versao=25"></script>
<script type="text/javascript">
    $(function(){
        $('#data_nascimento').mask('99/99/9999');
        $('#cpf').mask('999.999.999-99');
    });
</script>