<section class="content-header">
		  <h1>
			Lista de Exames 
			<small></small>
		  </h1>
		  <ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li><a href="Exames">Exames</a></li>
			<li class="active">Lista de Exames</li>
		  </ol>
</section>       

<section class="content"> 
	<div class="box">
		<div class="box-body"> 

	<div style="margin: 15px 0;">

		<label style="display: block;">Paciente</label>
		<input type="text" name="paciente" id="paciente" value="<?php print $this->q; ?>" style="width: 40%;">
		<button id="btn_busca" class="btn btn-default">Buscar</button>
		<button id="btn_limpar" class="btn btn-default">Remover Filtro</button>

	</div>  

	<table width="100%" border="0" cellpadding="5" cellspacing="1" style="font-size:12px;" class="table table-striped">
	  <tr style="font-weight:bold">
		<td width="20" style="text-align: center;">P</td>
		<td width="100">Clínica</td>
		<td>Data Criação</td>
		<td>Exame</td>
		<td>Paciente</td>
        <td style="text-align: center;">Código Paciente</td>
        <td style="text-align: center;">Data Nascimento</td>
        <td style="text-align: center;">CPF</td>
		<td width="138"></td>
	  </tr>

	<?php  foreach($view_list as $dados ) { ?>		

	   <tr class="line">
		<td style="text-align: center;">
			<div style="width: 20px; height: 20px; border-radius: 50%; background-color: <?php echo $dados['ativo'] == 'ativo' ? 'green' : 'red'; ?>;"></div>
		</td>
		<td><?php print strtoupper($dados["clinica_exame"]);?></td>
        <td><?php 

        $data = explode(" ", $dados['date_created']);

        print date('d/m/Y', strtotime($data[0]));

        ?> </td>
		
		<td><?php print html_entity_decode($dados["exame"]); ?></td>
		<td><?php print $dados["paciente"]; ?></td>
        <td style="text-align: center;"><?php print $dados["codigo_paciente"]; ?></td>
        <td style="text-align: center;"><?php print date('d/m/Y', strtotime($dados["data_nascimento_exame"])); ?></td>
		<td style="text-align: center;">
			<?php 
			if (empty($dados["cpf_user"])) {
				print "Problemas no cadastro do Paciente";
			} else {
				print $this->formatCPF($dados["cpf_user"]);
			}
			?>
		</td>

        <td class="actions" width="200" style="text-align: right;">

			<?php 

				$exames_geral = unserialize($dados['pdf']);

				$toCopy = "<p>Exame: ".$dados['exame'] ." | Data: ".implode('-', array_reverse(explode('-', $data[0])))."</p>";

				foreach($exames_geral as $ex) { 

					$toCopy .= "<p> [ ". @$ex['name'] ." - ".PATH. "themes/files/uploads/".$ex['file']." ] </p>";
			
				} 

			?>

            <div style="display: none;" id="toCopy_<?php print $dados['id_exames']; ?>">
                <?php print $toCopy; ?>
            </div>

			<a href="admin/pacientes/list_exames/<?php print empty($dados['id_pacientes']) ? 'codigo/'.$dados['codigo_paciente'].'?name='.$dados['paciente'] : 'id/'.$dados['id_pacientes']; ?>" class="btn btn-success btn-sm m-l-xs">
				<i class="fa fa-heartbeat" aria-hidden="true"></i>
			</a>

            <!-- <a href="javascript:void(0)" onclick="copyToClipboard('#toCopy_<?php print $dados['id_exames']; ?>')" class="btn btn-primary btn-sm">
                <i class="fa fa-copy"></i>
            </a> -->

            <!-- <a href="admin/index/cartao/id/<?php print $dados['codigo_paciente'] ?>" target="_blank" class="btn btn-primary btn-sm">
                <i class="fa fa-eye"></i>
            </a>  -->

            <?php if ($this->testaDias($dados['date_created'], 45) || $this->getUserType() == 4 || $this->getUserType() == 2 || $this->getUserType() == 1) { ?>
                <a href="admin/exames/edit_new/id/<?php print $dados['id_exames'] ?>" class="btn btn-primary btn-sm">
                    <i class="fa fa-edit"></i>
                </a>
            <?php } ?>  

            <a href="javascript:void(0)" class="del btn btn-danger btn-sm" data-controller="admin/exames/del" title="Apagar registro" data-id="<?php print $dados['id_exames']; ?>">
                <i class="fa fa-ban"></i>
            </a>

		</td>

	  </tr>

	<?php  }  ?>

	</table>

		</div>
	</div>

	<?php $this->pagination->paginate()?>

</section>

<script type="text/javascript">
	
	$(function(){

		new Clipboard('.copy');

		$('#btn_busca').click(function(){

			var paciente = $('#paciente').val();

			window.location.href = "admin/exames/exames_new?q="+encodeURI(paciente);
		});

		$('#btn_limpar').click(function(){

			window.location.href = "admin/exames";
		});

		$('.copy').click(function(){
		});
		
	});

	function copyToClipboard(element) {
	  var $temp = $("<input>");
	  $("body").append($temp);
	  $temp.val($(element).text()).select();
	  document.execCommand("copy");
	  $temp.remove();

	  alert("copiado com sucesso!");
	}

</script>
