<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">



<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<base href="<?php print PATH; ?>"  />

<?php print $this->get_head(); ?>



<?php if(isset($this->meta)) echo $this->meta; ?>



<base href="<?php //print PATH; ?>"  />



<title><?php //print $this->title; ?></title>





</head>    



<body data-color="grey" class="flat" style="">



	   		<?php $this->getPageView($this->vars); ?>

	

</body>



</html>